spring:
  application:
    name: resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://esignet.ltsstaging.fayda.et
          audiences: http://localhost
  resources:
    static-locations=classpath:/static/
server:
  port : 8090